name: prayer_times_app
description: "Prayer Times App for Europe and Germany"
publish_to: 'none'
version: 3.1.0+6

environment:
  sdk: ^3.7.2 # Ø­Ø§ÙØ¸ Ø¹Ù„Ù‰ Ø¥ØµØ¯Ø§Ø± Ø§Ù„Ù€ SDK Ø§Ù„Ù…ØªÙˆØ§ÙÙ‚

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # ğŸ’¡ Ø­Ø²Ù… Ø§Ù„Ù…Ø¹Ù…Ø§Ø±ÙŠØ© ÙˆØ¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø­Ø§Ù„Ø©
  flutter_riverpod: ^3.0.3  # ğŸŒŸ Ø§Ù„Ø£Ø³Ø§Ø³ Ø§Ù„Ù…Ø¹Ù…Ø§Ø±ÙŠ (MVVM)
  flutter_hooks: ^0.21.3+1     # Ù…ÙˆØµÙ‰ Ø¨Ù‡Ø§ Ù„Ø§Ø³ØªØ®Ø¯Ø§Ù… ConsumerWidget Ùˆ Clean UI
  hooks_riverpod: ^3.0.3
  google_mobile_ads: ^6.0.0
  provider: ^6.1.5+1

  # Ø­Ø²Ù… Ø­Ø³Ø§Ø¨ Ø§Ù„Ø£ÙˆÙ‚Ø§Øª ÙˆØ§Ù„Ù…ÙˆÙ‚Ø¹
  adhan: ^2.0.0+1
  geolocator: ^13.0.4
  geocoding: ^4.0.0
  
  # Ø­Ø²Ù… Ø§Ù„ØªØ§Ø±ÙŠØ® ÙˆØ§Ù„ÙˆÙ‚Øª
  intl: ^0.20.2 
  hijri: ^3.0.0 
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1 
  
  # Ø­Ø²Ù… Ø§Ù„ØªØ®Ø²ÙŠÙ† ÙˆØ§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1 

  
  # Ø­Ø²Ù… Ø§Ù„ÙˆØ§Ø¬Ù‡Ø© ÙˆØ§Ù„Ù€ UI
  google_fonts: ^6.3.3
  flutter_svg: ^2.2.3
  riverpod: ^3.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  #ios
  path_provider: ^2.1.5

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  # ğŸ”¹ Ø§Ù„Ù„ÙˆÙ† Ø§Ù„Ø£Ø³Ø§Ø³ÙŠ Ù„Ù„Ø®Ù„ÙÙŠØ© (Ø£Ø³ÙˆØ¯ Ù…Ø§Ø¦Ù„ Ù„Ù„Ø£Ø®Ø¶Ø± Ù„ÙŠÙ†Ø§Ø³Ø¨ Ø§Ù„Ø«ÙŠÙ…)
  color: "#000000"

  # ğŸ”¹ ØµÙˆØ±Ø© Ø§Ù„Ù„ÙˆØ¬Ùˆ ÙÙŠ Ø§Ù„Ù…Ù†ØªØµÙ (ØªÙ‚Ø¯Ø± ØªØºÙŠÙ‘Ø±Ù‡Ø§ Ù„Ùˆ ØªØ­Ø¨)
  image: assets/images/icon.png

  # ğŸ”¹ ØªÙØ¹ÙŠÙ„ Ù„ÙƒÙ„ Ù…Ù† Ø£Ù†Ø¯Ø±ÙˆÙŠØ¯ Ùˆ iOS
  android: true
  ios: true

  # ğŸ”¹ Ø¥Ø¹Ø¯Ø§Ø¯ Ø®Ø§Øµ Ù„Ø£Ù†Ø¯Ø±ÙˆÙŠØ¯ 12+
  android_12:
    color: "#000000"
    image: assets/images/icon.png

  # (Ø§Ø®ØªÙŠØ§Ø±ÙŠ) Ù„Ùˆ Ø­Ø§Ø¨ Ù†ÙØ³ Ø§Ù„Ø´Ø§Ø´Ø© ÙÙŠ Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„ÙØ§ØªØ­ / Ø§Ù„Ø¯Ø§ÙƒÙ†
  # color_dark: "#000000"
  # image_dark: assets/images/icon.png



flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/audio/
    - assets/hisn_al_muslim.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
